name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set Environment Variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install System Dependencies
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool pkg-config libltdl-dev libx11-dev

    - name: Run Workflow
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: (cmake --workflow --preset default; exit 0)

    - name: Run Workflow
      if: ${{matrix.os != 'ubuntu-latest'}}
      run: cmake --workflow --preset default

    - name: Print Failure Log
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        cat /home/runner/work/scintilla-example/scintilla-example/vcpkg/buildtrees/libxcrypt/autoconf-x64-linux-out.log
        cat /home/runner/work/scintilla-example/scintilla-example/vcpkg/buildtrees/libxcrypt/autoconf-x64-linux-err.log
